# Site settings
title: Kevin Truong
email: tig3r86@gmail.com
description: Web Specialist // Traveller // Entrepreneur

# Build settings

markdown: kramdown
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested